parameters:
  module.subpanel.top_buttons:
    SubPanelTopSelectButton:
      key: select
      labelKey: LBL_LINK
      action: select
      modes:
        - list
      acl:
        - edit
    SubPanelTopButtonQuickCreate: &createButton
      key: create
      labelKey: LBL_QUICK_CREATE
      action: create
      modes:
        - list
      acl:
        - edit
    SubPanelTopFilterButton:
      key: show-filter
      icon: filter
      labelKey: LBL_FILTER
      action: show-filter
      params:
        expanded: true
      modes:
        - list
      acl:
    SubPanelFilterClearButton:
      key: clear-filter
      labelKey: LBL_CLEAR_FILTER
      action: clear-filter
      params:
        collapsedMobile: true
        expanded: true
      modes:
        - list
      acl:
    SubPanelTopCreateButton: *createButton
    SubPanelTopCreateTaskButton:
      key: create
      labelKey: LNK_NEW_TASK
      action: create
      modes:
        - list
      acl:
        - edit
      module: tasks
    SubPanelTopScheduleMeetingButton:
      key: create
      labelKey: LNK_NEW_MEETING
      action: create
      modes:
        - list
      acl:
        - edit
      module: meetings
    SubPanelTopScheduleCallButton:
      key: create
      labelKey: LNK_NEW_CALL
      action: create
      modes:
        - list
      acl:
        - edit
      module: calls
    SubPanelTopComposeEmailButton:
      key: create
      labelKey: LNK_NEW_EMAIL
      action: create
      modes:
        - list
      acl:
        - edit
      module: emails
      moduleAction:
        - composeView
    SubPanelTopCreateNoteButton:
      key: create
      labelKey: LNK_NEW_NOTE
      action: create
      modes:
        - list
      acl:
        - edit
      module: notes
    SubPanelTopArchiveEmailButton:
      key: create
      labelKey: LBL_TRACK_EMAIL_BUTTON_LABEL
      action: create
      modes:
        - list
      acl:
        - edit
      module: emails
    SubPanelTopCreateLeadNameButton:
      key: create
      labelKey: LBL_QUICK_CREATE
      action: create
      modes:
        - list
      acl:
        - edit
      module: leads
