parameters:
  record.fields.grouped_fields_type_map:
    fullname:
      groupFields:
        - salutation
        - first_name
        - last_name
      layout:
        - salutation
        - first_name
        - last_name
      display: inline
      showLabel:
        - edit
    address:
      layout:
        - street
        - postalcode
        - city
        - state
        - country
      display: vertical
      showLabel:
        - edit


