parameters:
  module.listview.bulk_action:
    default:
      actions:
        delete:
          key: delete
          labelKey: LBL_DELETE
          params:
            min: 1
            displayConfirmation: true
            confirmationLabel: NTC_DELETE_CONFIRMATION_MULTIPLE
          acl:
            - delete
        export:
          key: export
          labelKey: LBL_EXPORT
          params:
            min: 1
          acl:
            - export
        merge:
          key: merge
          labelKey: LBL_MERGE_DUPLICATES
          params:
            min: 2
            max: 5
          acl:
            - edit
            - delete
        massupdate:
          key: massupdate
          labelKey: LBL_MASS_UPDATE
          params:
            allowAll: false
            min: 2
            max: 200
            recordPanel:
              title: LBL_MASS_UPDATE
              #fields are populated by a mapper
              #fields:
              mode: massupdate
              actions:
                - key: cancel
                  labelKey: LBL_CANCEL
                  modes: ['massupdate']
                - key: bulk-action
                  labelKey: LBL_SUBMIT_BUTTON_LABEL
                  modes: ['massupdate']
                  klass: ['btn', 'btn-danger', 'btn-sm']
                  params:
                    allowAll: false
                    min: 2
                    max: 200
                    bulkAction: massupdate
                    displayConfirmation: true
                    confirmationLabel: LBL_BULK_ACTION_MASS_UPDATE_CONFIRMATION
          acl:
            - massupdate
          availability:
            - acls
            - massupdate
    modules:
      employees:
        exclude:
          - delete
          - merge
